export function getAboutText(script){
    return aboutTexts[script];
}
let aboutTexts = {
    Nko: "N'Ko (N'Ko: ߒߞߏ) is a script devised by Solomana Kante in 1949, as a modern writing system for the Mandé languages of West Africa. The term N'Ko, which means I say in all Mandé languages, is also used for the Mandé literary standard written in N'Ko script. The script is written in a right-to-left direction  and the letters which are connected at the base.It is obligatory to mark both tone and vowels. N'Ko tones are marked as diacritics.Kante created N'Ko to provide a better way to write Mandé languages, which had for centuries been written in predominately in Ajami script, which was not perfectly suited to the tones unique to Mandé and common to many West African languages. Kante devised N'Ko as he was in Bingerville, Côte d'Ivoire and later brought to Kante's natal region of Kankan, Guinea. N'Ko began to be used in many educational books when the script is believed to have been finalized on April 14, 1949 (now N'Ko Alphabet Day); Kante had transcribed from religious to scientific and philosophical literature, even a dictionary.These materials were given as gifts into other Mandé-speaking parts of West Africa. The script received its first specially made typewriter from Eastern Europe back when Guinea had ties with the Soviet Union in the 1950s. The introduction of the script led to a movement promoting literacy in the N'Ko script among Mandé speakers in both Anglophone and Francophone West Africa. N'Ko literacy was instrumental in shaping the Maninka cultural identity in Guinea, and it has also strengthened the Mandé identity in other parts of West Africa. N’ko script has been used to write many non Mande West African languages as well including Mooré , Twi, and Yoruba as well as Bantu languages like Swahili and Lingala.",
    Adlam: "The Adlam script is a script used to write Fulfulde, the Fulani language (also known as Peuhl or Pulaar). The name Adlam is an acronym derived from the first four letters of the alphabet (A, D, L, M), standing for Alkule Dandayɗe Leñol Mulugol (𞤀𞤤𞤳𞤵𞤤𞤫 𞤁𞤢𞤲𞤣𞤢𞤴𞤯𞤫 𞤂𞤫𞤻𞤮𞤤 𞤃𞤵𞤤𞤵𞤺𞤮𞤤), which means the alphabet that protects the peoples from vanishing. Abdoulaye and Ibrahima Barry grew up in Guinea, West Africa. Few people in their town could read, and their father, who could, acted as a designated reader. The existing ways to write Fulfulde gave only an inconsistent approximation of the sounds of the spoken language, so In 1989, Ibrahima, then fourteen, and Abdoulaye, then set about inventing Adlam. The first iteration was cursive, but people found it hard to discern the individual letters, so in their second iteration, the brothers separated the letters. When Ibrahima left to study at the University of Conakry, he took the script with him, and it began to be used in classes. To provide content, they wrote books of practical advice – how to conduct a healthy pregnancy, how to filter water to make it drinkable – and a newspaper. Today Adlam is used in Guinea as well as the 23 other West African countries where Fulfulde is spoken, and has also been used to write neighboring languages, such as Hausa."
}

export function getLanguageNameFromCode (languageCode) {
    return languages[languageCode];
}
let languages = {
    Nko: "N'Ko",
    Adlam: "Adlam",
}
